### ISSUE TITLE
Word category files missing

### ISSUE THREAD

**Issue by begab** [avaapm/SEMCATdataset2018#1]
The abstract of the [accompanying paper](https://arxiv.org/abs/1711.00331) mentions that
> we introduce a new dataset (SEMCAT) that contains more than 6,500 words semantically grouped under 110 categories.

After cloning the repo, there are 100 category files and 6238 word forms included under the `Category` directory.
Could you please provide the category files for the additional 10 categories not currently included in the repo as well?
Thanks in advance.

**Comment by avaapm** [comment]
Thank you for notification. We completed missing files and there are 110 category files from now on.

**Comment by begab** [comment]
Thanks for the update!
